name: msk-time-ci

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'
      - name: Install dependencies
        run: pip3 install -r app_python/requirements.txt
      - name: Run pylint
        run: pylint -rn **/*.py
      - name: Run pycodestyle
        run: pycodestyle **/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'
      - name: Install dependencies
        run: pip3 install -r app_python/requirements.txt
      - name: Run pytest
        run: PYTHONPATH=. pytest app_python/tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_python
          file: ./app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moscow_time_python:latest
